#!/bin/bash
# Run the test, collect results, add to the database
# Later use ait-plot
# Arnaldo Carvalho de Melo <acme@redhat.com>

TESTNAME=latrate
SERVER_MACHINE=$(hostname)
. ait.config
CONFIG_FILE=$1
. $CONFIG_FILE
CLIENT_APP=$AIT_DIR/ait-client-$TESTNAME
LOCK_STAT_DIR=lock_stat

# killall leftover clients
ssh $CLIENT_MACHINE killall $CLIENT_PROCESS_NAME

if [ -n "$LOG_FILE" ] ; then
	# Remove logfile from previous runs
	ssh $CLIENT_MACHINE rm $REPORT_DIR/$LOG_FILE
fi

# If /proc/lock_stat exists, reset it
if [ -f /proc/lock_stat ] ; then
	rm -f $LOCK_STAT_DIR/last
	echo 0 > /proc/lock_stat
fi

# remove old client report
ssh $CLIENT_MACHINE rm $REPORT_DIR/$REPORT_FILE

# Run the client
ssh $CLIENT_MACHINE $CLIENT_APP $SERVER_MACHINE $METRIC_RANGE > $REPORT_DIR/$REPORT_FILE

# If /proc/lock_stat exists, take a snapshot
if [ -f /proc/lock_stat ] ; then
	cat /proc/lock_stat > $LOCK_STAT_DIR/last
fi

if [ -n "$LOG_FILE" ] ; then
	rm -f $LOG_FILE
	# Get the client log file, to extract the client config
	scp $CLIENT_MACHINE:$REPORT_DIR/$LOG_FILE .
fi

# Get server information
./ait-get-sysinfo $SERVER_PROCESS_NAME > ${SERVER_MACHINE}.sysinfo

# Get client information
ssh $CLIENT_MACHINE $AIT_DIR/ait-get-sysinfo $CLIENT_PROCESS_NAME > ${CLIENT_MACHINE}.sysinfo

# Collect it!
./ait-db-add-$TESTNAME $DBNAME $CLIENT_MACHINE $SERVER_MACHINE $REPORT_DIR/$REPORT_FILE
