#!/bin/bash
# Run the test, collect results, add to the database
# Later use ait-plot
# Arnaldo Carvalho de Melo <acme@redhat.com>

SERVER_MACHINE=$(hostname)
. ait.config

if [ $# -ne 1 ] ; then
	echo "usage: ait-run config-file"
	exit 1
fi

CONFIG_FILE=$1

if [ ! -f $CONFIG_FILE ] ; then
	echo "$CONFIG_FILE not found!"
	exit 1
fi

. $CONFIG_FILE

if [ -z "$TESTNAME" ] ; then
	echo "TESTNAME variable not set and not present in $CONFIG_FILE"
	exit 1
fi

CLIENT_APP=$AIT_DIR/ait-client-$TESTNAME
LOCK_STAT_DIR=lock_stat

# killall leftover clients
ssh $CLIENT_MACHINE killall -q $CLIENT_PROCESS_NAME 

mkdir -p $REPORT_DIR 2> /dev/null

if [ -n "$LOG_FILE" ] ; then
	# Remove logfile from previous runs
	ssh $CLIENT_MACHINE rm $REPORT_DIR/$LOG_FILE
fi

# If /proc/lock_stat exists, reset it
if [ -f /proc/lock_stat ] ; then
	rm -f $LOCK_STAT_DIR/last
	echo 0 > /proc/lock_stat
fi

# remove old client report
ssh $CLIENT_MACHINE rm -f $REPORT_DIR/$REPORT_FILE

# Run the client
ssh $CLIENT_MACHINE $CLIENT_APP $SERVER_MACHINE $METRIC_RANGE > $REPORT_DIR/$REPORT_FILE

if [ $? -ne 0 ] ; then
	cat $REPORT_DIR/$REPORT_FILE
	exit 1
fi

# If /proc/lock_stat exists, take a snapshot
if [ -f /proc/lock_stat ] ; then
	cat /proc/lock_stat > $LOCK_STAT_DIR/last
fi

if [ -n "$LOG_FILE" ] ; then
	rm -f $LOG_FILE
	# Get the client log file, to extract the client config
	scp $CLIENT_MACHINE:$REPORT_DIR/$LOG_FILE .
fi

# Get server information
./ait-get-sysinfo $SERVER_PROCESS_NAME > ${SERVER_MACHINE}.sysinfo

# Get client information
ssh $CLIENT_MACHINE $AIT_DIR/ait-get-sysinfo $CLIENT_PROCESS_NAME > ${CLIENT_MACHINE}.sysinfo

mkdir -p reports/$TESTNAME/

# Collect it!
./ait-db-add-$TESTNAME $DBNAME $CLIENT_MACHINE $SERVER_MACHINE $REPORT_DIR/$REPORT_FILE

exit 0
